user_fields = [
    'ammo',
    'attacks',
    'attacksfull',
    'bars',
    'basic',
    'battlestats',
    'bazaar',
    'cooldowns',
    'crimes',
    'discord',
    'display',
    'education',
    'events',
    'gym',
    'hof',
    'honors',
    'icons',
    'inventory',
    'jobpoints',
    'log',
    'medals',
    'merits',
    'messages',
    'missions',
    'money',
    'networth',
    'newevents',
    'newmessages',
    'notifications',
    'perks',
    'personalstats',
    'profile',
    'properties',
    'receivedevents',
    'refills',
    'reports',
    'revives',
    'revivesfull',
    'skills',
    'stocks',
    'timestamp',
    'travel',
    'weaponexp',
    'workstats']

property_fields = ['property', 'timestamp']

faction_fields = [
    'applications',
    'armor', 
    'armorynews', 
    'attacknews', 
    'attacks', 
    'attacksfull', 
    'basic', 
    'boosters', 
    'cesium', 
    'chain', 
    'chainreport', 
    'chains', 
    'contributors', 
    'crimenews', 
    'crimes', 
    'currency', 
    'donations', 
    'drugs', 
    'fundsnews', 
    'mainnews', 
    'medical', 
    'membershipnews', 
    'positions', 
    'reports', 
    'revives', 
    'revivesfull', 
    'stats', 
    'temporary', 
    'territory', 
    'territorynews', 
    'timestamp', 
    'upgrades', 
    'weapons'
]

company_fields = [
    'applications', 'companies', 'detailed', 'employees', 'news', 'newsfull', 'profile', 'stock', 'timestamp'
]

market_fields = [
    'bazaar', 'itemmarket', 'pointsmarket', 'timestamp'
]

generic_fields = [
    'bank', 
    'cards', 
    'chainreport', 
    'cityshops', 
    'companies', 
    'competition', 
    'education', 
    'factiontree', 
    'gyms', 
    'honors', 
    'items', 
    'itemstats', 
    'logcategories', 
    'logtypes', 
    'medals', 
    'organisedcrimes', 
    'pawnshop', 
    'pokertables', 
    'properties', 
    'rackets', 
    'raids', 
    'rankedwarreport', 
    'rankedwars', 
    'stats', 
    'stocks', 
    'territory', 
    'territorywars', 
    'timestamp'
]